{%extends "common/layout.phtml"%}
{%block content%}
<form class="form-signin" method="post" action="/web/user/signIn">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="phone" name="username" id="inputUsername" class="form-control" placeholder="Phone" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
    {% for msg in errorMsg %}
    <div class="alert alert-danger" role="alert">{{msg}}</div>
    {% endfor %}
    <input type="hidden" name="csrf_token" value="{{token}}">
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
{%endblock%}
