<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/user_signup.css">
    <title>User sign up</title>
</head>
<body>
<form class="form-signin" method="post" action="/web/user/signup">
    <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="phone" name="username" id="inputUsername" class="form-control" placeholder="Phone" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <label for="inputRepeatPassword" class="sr-only">Repeat Password</label>
    <input type="password" name="password_confirmation" id="inputRepeatPassword" class="form-control" placeholder="Repeat Password" required>
    <?php
        foreach ($errorMsg as $field => $msg):
    ?>
            <div class="alert alert-danger" role="alert"><?=$msg?></div>
    <?php
        endforeach;
    ?>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
</form>

<script src="/js/jquery.slim.min.js"></script>
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>