{%extends "common/articleLayout.phtml"%}

{%block content%}
<main role="main" class="container">
        {% for item in articles %}
        <div class="article-item">
                <a class="article-title" href="/post/{{item.id}}"> <h2>{{item.title}}</h2> </a>
                <p class="article-summary">
                    {{item.summary}}
                </p>
                <p class="article-ext">
                    <a href="/post/{{item.id}}" class="article-detail">详细内容&gt;&gt; </a> &nbsp; {{item.created_at}}
                </p>
        </div>
        {% endfor %}
</main>
{%endblock%}