<html>
<head>
    <title>Welcome Page Title</title>
</head>
<body>
<style>
    .content{width:100%;min-height: 400px;text-align: center;line-height: 400px;font-size:62px;font-family: 'Menlo', 'Monaco', monospace}
</style>
    <div>
        <a href="/web/user/logOut">注销登录</a>
    </div>
    <div>
        <a href="/web/user/signIn">登录</a>
    </div>
    <div class="content">
        <?=$content;?>
    </div>
</body>
</html>